site_name: CS479 Machine Learning for 3D Data (KAIST, Spring 2026)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - macros

copyright: Copyright &copy; 2026 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - 3D Segmentation Competition: 3d-segmentation-competition.md
  - 3D Rendering Contest: 3d-rendering-contest.md

extra:
  analytics:
    provider: google
    property: G-0DGDW2727H
  links:
    lec01: https://onedrive.live.com/?redeem=aHR0cHM6Ly8xZHJ2Lm1zL2IvYy82MDU2MjAyM2I2NjQwMjgyL0lRQ2VxbUNrdVlmY1Q0d25weEdCb0FYNkFYUWZPMDExdng4X05xWG1INDhPcnB3P2U9UUdvdDUx&cid=60562023B6640282&id=60562023B6640282%21sa460aa9e87b94fdc8c27a71181a005fa&parId=60562023B6640282%21s09a74fd3aa1248158a75e9b0ae1dbf44&o=OneUp
    asgmt1: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-PointNet
    asgmt2: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-NeRF
    asgmt3: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-3DGS
    asgmt4: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-MLS-MS
    demo: https://github.com/KAIST-Visual-AI-Group/CS479-Assignment-NeRF-Applications
